### ISSUE TITLE
yarn ci-check 

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/carbon-tutorial-vue#100]
https://www.carbondesignsystem.com/tutorial/vue/step-5/#continuous-integration-ci-check

The ci-check hasn't been added to this project. 

It either needs to be added or removed from the instructions.

**Comment by lee-chase** [comment]
Issue resolved https://github.com/carbon-design-system/carbon-tutorial-vue/commit/cef64e85dc754e9a802aa7d7620af7ad9a9a83c1
